### ISSUE TITLE
Memory gets used up really quickly when run as daemon

### ISSUE THREAD

**Issue by jason-edwards** [jason-edwards/price-visualiser#1]
Memory runs out when run as daemon in about a minute. Not sure if happens when run in non-daemon mode.

**Comment by shalvin** [comment]
Ooops still logged into your account

**Comment by jason-edwards** [comment]
Cannot reproduce using daemon or otherwise.
Was this on the AWS EC2 server or on your local machine?
I have been running it for 5 mins without it exceeding 6% memory.

ubuntu@...  :~/Trial/price-visualiser$ ps aux | grep main.py
root     12909  1.5  4.4 247724 45212 ?        Sl   10:18   0:05 python main.py start

**Comment by shalvin** [comment]
Sorry i haven't had a chance to reproduce this out yet, I'll try when I get home from work. 
It was on EC2 while run as a daemon. I had vim open and was changing some stuff then I couldn't do anything and had to restart. I might be wrong, it could be something else. Also, have you changed the swap bkac to a smaller size since building phantomjs?
